#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v26
# autospec commit: 99a7985
#
Name     : metis
Version  : 5.1.0
Release  : 14
URL      : https://karypis.github.io/glaros/files/sw/metis/metis-5.1.0.tar.gz
Source0  : https://karypis.github.io/glaros/files/sw/metis/metis-5.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: metis-bin = %{version}-%{release}
Requires: metis-lib = %{version}-%{release}
Requires: metis-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This file contains some test graphs and meshes
4elt.graph
copter2.graph
mdual.graph
These are small to medium size graphs corresponding to 2D and 3D
finite element mesh. They can be used as inputs to gpmetis and ndmetis.

%package bin
Summary: bin components for the metis package.
Group: Binaries
Requires: metis-license = %{version}-%{release}

%description bin
bin components for the metis package.


%package dev
Summary: dev components for the metis package.
Group: Development
Requires: metis-lib = %{version}-%{release}
Requires: metis-bin = %{version}-%{release}
Provides: metis-devel = %{version}-%{release}
Requires: metis = %{version}-%{release}

%description dev
dev components for the metis package.


%package lib
Summary: lib components for the metis package.
Group: Libraries
Requires: metis-license = %{version}-%{release}

%description lib
lib components for the metis package.


%package license
Summary: license components for the metis package.
Group: Default

%description license
license components for the metis package.


%prep
%setup -q -n metis-5.1.0
cd %{_builddir}/metis-5.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1746826937
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DGKLIB_PATH=../GKlib -DSHARED:BOOL=TRUE  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd graphs
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/gpmetis test.mgraph 4
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/gpmetis 4elt.graph
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/gpmetis copter2.graph 4
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/gpmetis mdual.graph
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/ndmetis 4elt.graph
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/ndmetis copter2.graph 4
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/ndmetis mdual.graph
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/mpmetis metis.mesh 2
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/m2gmetis metis.mesh 2
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/ndmetis mdual.graph
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/ndmetis mdual.graph
LD_LIBRARY_PATH=%{buildroot}/usr/lib64:$LD_LIBRARY_PATH %{buildroot}/usr/bin/graphchk 4elt.graph
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1746826937
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/metis
cp %{_builddir}/metis-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/metis/a7c3a4f7dcf7a014c7dfdd3f8752d699eb7f7c2e || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd
## install_append content
mkdir -p %{buildroot}/usr/lib64
mv %{buildroot}/usr/lib/* %{buildroot}/usr/lib64

## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cmpfillin
/usr/bin/gpmetis
/usr/bin/graphchk
/usr/bin/m2gmetis
/usr/bin/mpmetis
/usr/bin/ndmetis

%files dev
%defattr(-,root,root,-)
/usr/include/metis.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmetis.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/metis/a7c3a4f7dcf7a014c7dfdd3f8752d699eb7f7c2e
